
msg:
  title: Bamberg Beverage Box

spring:
  thymeleaf:
    mode: HTML
    cache: false # Disable caching for development
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    template-resolver-order: 1 # Set the order for template resolving
    dialects:
      - org.thymeleaf.extras.springsecurity5.dialect.SpringSecurityDialect # Use the correct version
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 1500MB
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 600
          must-revalidate: true
  jpa:
    open-in-view: false
  messages:
    basename: messages/title/messages,messages/errors/error_messages,messages/success/success_messages,messages/menu/menu_messages,messages/validation/validation_messages,messages/label/label_messages,messages/breadcrumb/breadcrumb_messages

  profiles:
    active: nafees

server:
  http2:
    enabled: true
  servlet:
    context-path:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  port: 9092

login:
  url: http://localhost:9092/
  default-success-url: http://localhost:9092/
